#opt
train_epoch: 150           # number of epochs
B: 1                 # batch size
warmup_epoch: 0    # number of warm-up epochs
wd: 0.00001               # weight decay
lr: 0.0002
min_lr: 0

#dset
dataset: camelyon16
n_class: 2                            # number of classes
n_worker: 8                          # number of workers
pin_memory: False                     # use pin memory in dataloader
n_shot: -1


dataset_root: 
persistence: False
same_psize: 0

# pretrained
pretrain: 'Resnet50'

D_feat: 1024
D_inner: 256


